"use server";

import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export async function createCosignInvite(formData: FormData) {
  const projectId = String(formData.get("projectId") ?? "").trim();
  const collaboratorName = String(formData.get("collaboratorName") ?? "").trim();

  if (!projectId || !collaboratorName) {
    throw new Error("Missing fields");
  }

  const supabase = await createSupabaseServerClient();

  // Verify the requester is the project owner
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  const { data: project } = await supabase
    .from("projects")
    .select("user_id")
    .eq("id", projectId)
    .single();

  if (!project || project.user_id !== user.id) {
    throw new Error("Not authorized");
  }

  // Delete any existing pending invite for this collaborator on this project
  await supabase
    .from("cosign_invites")
    .delete()
    .eq("project_id", projectId)
    .eq("collaborator_name", collaboratorName)
    .eq("status", "pending");

  // Create a new invite (token auto-generated by DB default)
  const { data, error } = await supabase
    .from("cosign_invites")
    .insert({ project_id: projectId, collaborator_name: collaboratorName })
    .select("token")
    .single();

  if (error || !data) {
    console.error(error);
    throw new Error("Could not create invite");
  }

  revalidatePath(`/project/${projectId}`);
  return data.token as string;
}
